version: "3.9"
services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8081:8081"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/conf/conf.d
        target: /etc/nginx/conf.d
      # - type: bind
      #   source: ../dcdata/nginx/logs
      #   target: /data/wwwlogs
      - type: volume
        source: wwwroot
        target: /data/wwwroot
        volume:
          nocopy: true
#      - ../dcdata/nginx/logs/:/data/wwwlogs/:rw
#      - ../wwwroot/:/data/wwwroot/:rw
#      - ./nginx/conf/conf.d:/etc/nginx/conf.d/:ro
#      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1G
    restart: always
    networks:
      - net-www

  php74:
    build:
      context: ./php74/build/
    expose:
      - "9000"
    # ports:
    #   # - "9003:9003"
    volumes:
      - type: bind
        source: ./php74/conf/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ./php74/conf/php-fpm.conf
        target: /usr/local/etc/php-fpm.d/www.conf
      - type: volume
        source: wwwroot
        target: /data/wwwroot
        volume:
          nocopy: true
      - type: volume
        source: vscode-server
        target: /root/.vscode-server
        volume:
          nocopy: true
      - type: bind
        source: ../share-data/test/
        target: /share-data
#      - type: bind
#        source: ../share-data/m24.local/
#        target: /data/wwwroot/m24.local
      # - type: tmpfs
      #   target: /data/wwwroot/m24.local/generated
#        tmpfs:
#          size: 1000
#      - type: tmpfs
#        target: /data/wwwroot/m24.local/var
#      - type: tmpfs
#        target: /data/wwwroot/m24.local/pub/static
    restart: always
    command: ["php-fpm","-R"]
    # environment:
    #   XDEBUG_CONFIG : "mode=debug client_host=host.docker.internal client_port=9003 start_with_request=yes idekey=PHPSTORM"
    #   PHP_IDE_CONfIG: "serverName=my.local"
    extra_hosts:
      - "m24.local:10.113.3.211"
    networks:
      - net-www
      - net-storage

  composer:
    build:
      context: ./composer/build/
    volumes:
      - type: volume
        source: wwwroot
        target: /data/wwwroot
        volume:
          nocopy: true
      # - type: volume
      #   source: mysql8-data
      #   target: /data/dcdata/mysql8-data
      #   volume:
      #     nocopy: true
      # - type: volume
      #   source: redis-data
      #   target: /data/dcdata/redis-data
      #   volume:
      #     nocopy: true
      # - type: volume
      #   source: es-7-10-data
      #   target: /data/dcdata/es-7-10-data
      #   volume:
      #     nocopy: true

  mysql8:
    image: mysql:8
#    expose:
#      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./mysql8/conf/mysql.cnf
        target: /etc/mysql/conf.d/mysql.cnf
#        read_only: true
      - type: volume
        source: mysql8-data
        target: /var/lib/mysql
        volume:
          nocopy: true
      # - type: bind
      #   source: ../dcdata/mysql8/data
      #   target: /var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password #允许远程访问
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - net-storage
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 2G

  redis:
    image: redis:alpine
    volumes:
      - type: bind
        source: ./redis/conf/redis.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: redis-data
        target: /data
        volume:
          nocopy: true
    ports:
      - 6379:6379
    command:
      redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    restart: always
    networks:
      - net-storage

  es-7-10:
#    image: elasticsearch:7.10.1
    build:
      context: ./es-7-10/build/
#    container_name: elasticsearch
    volumes:
      - type: volume
        source: es-7-10-data
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
      - type: bind
        source: ./es-7-10/kuromojo/search_dic.csv
        target: /usr/share/elasticsearch/search_dic.csv
      - type: bind
        source: ./es-7-10/kuromojo/synonym.txt
        target: /usr/share/elasticsearch/synonym.txt
      - type: bind
        source: ./es-7-10/kuromojo/search_dic.csv
        target: /usr/share/elasticsearch/config/search_dic.csv
      - type: bind
        source: ./es-7-10/kuromojo/synonym.txt
        target: /usr/share/elasticsearch/config/synonym.txt
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net-storage

  sftp:
    build:
      context: ./sftp-server/build/
    ports:
        - "2222:22"
    volumes:
      - type: volume
        source: wwwroot
        target: /data/root
        volume:
          nocopy: true
    environment:
      PUBLICHOST: "localhost"
    restart: always
    networks:
      - net-storage

volumes:
  mysql8-data:
    external: true
  redis-data:
    external: true
  es-7-10-data:
    external: true
  wwwroot:
    external: true
  vscode-server:
    external: true
  test:
    external: true

networks:
  net-www:
  net-storage:
